{% set name = "paper-qa" %}
{% set version = "2025.12.19" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paper_qa-{{ version }}.tar.gz
  sha256: d6b80b10b31b5979b30aa5dfc12e12f238b6fb4b44a53276d4c3272a38103e7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - httpx-aiohttp
    - paper-qa-pypdf
    - fhlmi >=0.41.0
    - aiohttp >=3.10.6
    - anyio
    - fhaviary >=0.27
    - httpx
    - pybtex
    - pydantic-settings
    - pymupdf >=1.24.12
    - rich
    - setuptools
    - tantivy
    - tenacity
    - python >={{ python_min }}
    - html2text
    - numpy
    - pydantic >=2.0,<3.dev0,>=2.10.1
    - tiktoken >=0.4.0

test:
  imports:
    - paperqa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: LLM Chain for answering questions from docs
  home: https://github.com/whitead/paper-qa
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
