{% set name = "paper-qa" %}
{% set version = "4.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paper_qa-{{ version }}.tar.gz
  sha256: 512f6fe6ccadfb8755d084c2350a263a73b5afc25f0c180edc339f031d15295b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62.6.0
    - pip
  run:
    - python >=3.8
    - pycryptodome
    - html2text
    - numpy
    - openai >=1
    - pydantic >=2
    - pypdf
    - tiktoken >=0.4.0

test:
  imports:
    - paperqa
  commands:
    - pip check
  requires:
    - pip

about:
  summary: LLM Chain for answering questions from docs
  home: https://github.com/whitead/paper-qa
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
