{% set name = "paper-qa" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paper_qa-{{ version }}.tar.gz
  sha256: 40cf3e4248c44031cfa26df9cd6592d5f873cb7c56867d3e871b562c6f93218e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62.6.0
    - pip
  run:
    - aiohttp
    - anyio
    - fhaviary >=0.6
    - httpx
    - litellm >=1.44
    - pybtex
    - pydantic-settings
    - pymupdf
    - rich
    - setuptools
    - tantivy
    - tenacity
    - python >=3.8
    - pycryptodome
    - html2text
    - numpy
    - openai >=1
    - pydantic >=2.0,<3.dev0
    - pypdf
    - tiktoken >=0.4.0

test:
  imports:
    - paperqa
  commands:
    - pip check
  requires:
    - pip

about:
  summary: LLM Chain for answering questions from docs
  home: https://github.com/whitead/paper-qa
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
