{% set name = "paper-qa" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paper_qa-{{ version }}.tar.gz
  sha256: 81e89b80df2cb3554d93a86d42eec7de4777b412c04526b093c2d64dad117743

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62.6.0
    - pip
  run:
    - coredis
    - limits
    - aiohttp
    - anyio
    - fhaviary >=0.10.2
    - httpx
    - litellm >=1.44
    - pybtex
    - pydantic-settings
    - pymupdf >=1.24.12
    - rich
    - setuptools
    - tantivy
    - tenacity
    - python >=3.8
    - pycryptodome
    - html2text
    - numpy
    - openai <1.47
    - pydantic >=2.0,<3.dev0,>=2.10.1
    - pypdf
    - tiktoken >=0.4.0

test:
  imports:
    - paperqa
  commands:
    - pip check
  requires:
    - pip

about:
  summary: LLM Chain for answering questions from docs
  home: https://github.com/whitead/paper-qa
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
